### ISSUE TITLE
Panel folder contains copy of mainboard files, not panel files

### ISSUE THREAD

**Issue by ryokell** [jsenzel1/petrock#4]
It looks like the panel folder just contains a copy of the same files as the board folder at the moment, not the panel files as expected.

**Comment by jsenzel1** [comment]
hm, redownloaded and put em into kicad, looks like the panel files to me, maybe give it a once over and if its still not working I can just reupload?

**Comment by ryokell** [comment]
ahh I see - apologies, the files all being named identically threw me off. It looks like they are indeed correct after all!
